# Generated by Django 2.2.1 on 2019-12-23 14:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191202_1629'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vacancy',
            managers=[
                ('itVacancies', django.db.models.manager.Manager()),
            ],
        ),
    ]
