# Generated by Django 2.2.1 on 2019-12-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191130_2111'),
        ('users', '0002_auto_20191130_2110'),
    ]

    operations = [
    ]
