# Generated by Django 2.2.1 on 2019-12-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20191202_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='industry',
            field=models.SmallIntegerField(choices=[(1, 'IT'), (2, 'BUSINESS'), (3, 'SERVICE'), (4, 'EDUCATION')], default=1),
            preserve_default=False,
        ),
    ]
