USER_COMPANY = 1
USER_WORKER = 2

USER_TYPES = (
    (USER_COMPANY, 'COMPANY'),
    (USER_WORKER, 'WORKER')
)

IT_INDUSTRY = 1
BUSINESS_INDUSTRY = 2
SERVICE_INDUSTRY = 3
EDUCATION_INDUSTRY = 4

INDUSTRY_TYPES = (
    (IT_INDUSTRY, 'IT'),
    (BUSINESS_INDUSTRY, 'BUSINESS'),
    (SERVICE_INDUSTRY, 'SERVICE'),
    (EDUCATION_INDUSTRY, 'EDUCATION')
)