IT_INDUSTRY = 1
BUSINESS_INDUSTRY = 2
SERVICE_INDUSTRY = 3
EDUCATION_INDUSTRY = 4

INDUSTRY_TYPES = (
    (IT_INDUSTRY, 'IT'),
    (BUSINESS_INDUSTRY, 'BUSINESS'),
    (SERVICE_INDUSTRY, 'SERVICE'),
    (EDUCATION_INDUSTRY, 'EDUCATION')
)