USER_COMPANY = 1
USER_WORKER = 2

USER_TYPES = (
    (USER_COMPANY, 'COMPANY'),
    (USER_WORKER, 'WORKER')
)

IT_INDUSTRY = 1
BUSINESS_INDUSTRY = 2
SERVICE_INDUSTRY = 3
EDUCATION_INDUSTRY = 4

INDUSTRY_TYPES = (
    (IT_INDUSTRY, 'IT'),
    (BUSINESS_INDUSTRY, 'BUSINESS'),
    (SERVICE_INDUSTRY, 'SERVICE'),
    (EDUCATION_INDUSTRY, 'EDUCATION')
)

MATCHED_BY_COMPANY = 1
MATCHED_BY_USER = 2
MATCHED_BY_BOTH = 3
DECLINED_BY_USER = 4
DECLINED_BY_COMPANY = 5

MATCHING_STATUSES = (
    (MATCHED_BY_COMPANY, 'MATCHED_BY_COMPANY'),
    (MATCHED_BY_USER, 'MATCHED_BY_USER'),
    (MATCHED_BY_BOTH, 'MATCHED_BY_BOTH'),
    (DECLINED_BY_USER, 'DECLINED_BY_USER'),
    (DECLINED_BY_COMPANY, 'DECLINED_BY_COMPANY'),
)